### ISSUE TITLE
Control over whether xsd:dateTime is converted

### ISSUE THREAD

**Issue by CyberDaedalus00** [rubensworks/sparqljson-to-tree.js#17]
I was wondering if there was any means keep the conversion of values of datatype xsd:dateTime from being converted creating the TreeConverter to materializeRdfJsTerms to true.

I didn't see anything in the code

**Comment by rubensworks** [comment]
Not sure if I understand the question, but setting `materializeRdfJsTerms` to `false` should work.

**Comment by CyberDaedalus00** [comment]
My bad... the debugger I was using was not showing me the actual data, but rather it formatted.  It actually working exactly like we needed and is a help in our solution.

**Comment by rubensworks** [comment]
Great to hear that 🙂
